import axios from 'axios'

export const HTTP = axios.create({
  baseURL: `http://localhost:8090/user`,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Max-Age': 86400,
    'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkeVlqaERPc0RneGRPT1FoRkZXZ1JQWk05NWZXVzFBVGl1NFFrMkRxM2NBIn0.eyJleHAiOjE2MjYyMzk2MTgsImlhdCI6MTYyNjIzNzgxOCwianRpIjoiOTY1MDQzYjEtNmI0ZS00N2M3LWFmNDQtMDg5ZWY0ZjgzYTA0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL1NwcmluZ0Jvb3QiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiMjI5MzE5MzQtOWMxZS00YTYyLThmZDQtOTgyNzBjMThmNjY1IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4iLCJzZXNzaW9uX3N0YXRlIjoiNmZhYzNjZWMtYWI1NS00MmE4LWFhYjctMjA3YjYzN2U2N2Q0IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyMSJ9.QQ6Qgtpu_ogwzzAlKJGy92ZxuTFfANrgwXRTBCZe6NhcSfzAGeTeNVWQRo1kiv1sdfd8zjbPDaiLv0TRBEr0g7bXIl8K_V2IZflmANqkF-aj7SJqYri2Gx8WnGusPgEibHatOEgH933KbxvzlEixBzRda9b-V3WILYOFGlOjy3LPeJbx4sS7O8-1iSEpHg2-JbmfTlpMV_u84Skv9bR-AvQjHRFtGo8JEXR4AEkoTgwz3ONAhJZMupVQZwEOv2vRw0pWnADGAq8t8DNdaRqUx27rw2QN9cJ7-wAtuT40SZyfhJ_viEpvYObbfHTtpTeFAu_H6GeM4K4u-VgUV1k_Dg'
  }
})
