#!/bin/bash
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 2 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 10 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 20 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 30 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 40 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 50 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 60 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 70 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 80 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 90 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 100 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 110 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 120 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 130 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 140 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 150 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 160 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 170 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 180 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 190 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 200 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 210 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 220 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 230 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 240 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 250 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 260 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 270 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 280 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 290 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 300 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 310 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 320 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 330 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 340 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 350 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 360 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 370 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 380 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 390 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 400 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 410 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 420 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 430 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 440 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 450 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 460 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 470 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 480 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 500 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 510 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 520 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 530 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 540 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 550 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 560 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 570 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 580 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 590 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 660 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 610 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 620 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 630 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 640 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 650 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 660 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 670 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 680 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 690 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 700 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 710 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 720 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 730 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 740 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 750 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 760 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 770 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 780 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 790 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 800 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 810 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 820 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 830 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 840 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 850 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 860 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 870 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 880 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 890 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 900 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 910 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 920 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 930 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 940 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 950 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 960 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 970 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 980 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 990 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1000 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1010 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1020 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1030 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1040 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1050 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1060 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1070 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1080 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1090 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1100 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1110 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1120 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1130 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1140 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1150 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1160 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1170 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1180 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1190 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1200 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1210 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1220 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1230 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1240 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1250 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1260 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1270 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1280 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1290 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1300 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1310 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1320 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1330 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1340 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1350 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1360 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1370 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1380 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1390 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1400 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1410 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1420 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1430 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1440 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1450 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1460 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1470 minutes &&
echo "sh /root/keycloak_management/demo/tasks/wake_up_frontend.sh" | at now + 1480 minutes