import axios from 'axios'

export const HTTP = axios.create({
  baseURL: `http://localhost:8090/`,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Max-Age': 86400,
    'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkeVlqaERPc0RneGRPT1FoRkZXZ1JQWk05NWZXVzFBVGl1NFFrMkRxM2NBIn0.eyJleHAiOjE2MjY0NjQwMDIsImlhdCI6MTYyNjM3NzYwMiwianRpIjoiYzk0ZjdjNDUtNzVlZC00ZGFlLTk5ZjktZTk0NzgyNDFiMTdhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL1NwcmluZ0Jvb3QiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiMjI5MzE5MzQtOWMxZS00YTYyLThmZDQtOTgyNzBjMThmNjY1IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4iLCJzZXNzaW9uX3N0YXRlIjoiZTQwNzIyMzYtNjQ2MC00MTk1LWFlZjQtNjUzNDUwOWRlNzBkIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctYXBwbGljYXRpb25zIiwidmlldy1jb25zZW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJtYW5hZ2UtY29uc2VudCIsImRlbGV0ZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyMSJ9.Yv8lyuUFp7vPVUZALAy_OotBkakrZsKb83loXNFjnViKF-JPLOTVttNw9PEYkeEl6exT8hNXN2GJqO8CNhgPKTE-hs1yZwcC1_lzZHORymWDo2blUFHHiiqLrDDsZ6Q0NS4Xwh4bh5cJ4kfV_XUDJUwgz_fLmcokPSb7nmgR8s9q5TX0WzBl1CWg-8O_08dcEihV0CvWV31Pyf_VZ0Ay5ZH5q2EvFFvQagDNVu2KxGhfEPbT5VdDsEaPgl5UEHmS_-oVXejuQUMMHb1xG2M1hyt8D4DCmFWLxs0uCKc8WKXJaxb_eo4Yo7WST6Bd-PN_bH4QMcvCIzHw2JiRlpK5sA'
  }
})
