import axios from 'axios'

export const HTTP = axios.create({
  baseURL: `http://localhost:8090/`,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Max-Age': 86400,
    'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkeVlqaERPc0RneGRPT1FoRkZXZ1JQWk05NWZXVzFBVGl1NFFrMkRxM2NBIn0.eyJleHAiOjE2MjYyNzQ0MzcsImlhdCI6MTYyNjI3MjYzNywianRpIjoiMTc1MDRlYWMtYjkwZC00ODE2LTkyZjktYjE1Yjk0ZDQxOTZjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL1NwcmluZ0Jvb3QiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiMjI5MzE5MzQtOWMxZS00YTYyLThmZDQtOTgyNzBjMThmNjY1IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4iLCJzZXNzaW9uX3N0YXRlIjoiN2JhNWI1M2MtYjE0NS00YTdmLWI5YTItMjU2MDZmODU1ODljIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyMSJ9.FJGUpbfw8fVeHD9Sl1qMoR5YqpFxvu5egu2yhKcyUuyvEtWRdqMdlIRFKDaxKqOr-zp9OcLFSHSoo7dX-AGL38SeB6qAzaWSV7OEZ2CABiC2bxWbHQTu2CugjFSdOIECkoUUgMyYYG2XMP6zWWLUlB0-axJmoyOgjNLZo-ym6J0aNfEZgwiiGMyNMHZO-03pneDmmBsjnsuZg6SgV-TPoER3sWisUc_uCJNLv6zZXOzNLgHtv2iYM6t0Y3H7NReYjOiQvjthLJ5JCjC2SlWe4i4wy_wF2ymwHSRXoVriXJkX_wDL9I1uQHBvnTANpYjlFN_IxIpVZKzrrxAFTfpPHw'
  }
})
