import axios from 'axios'

export const HTTP = axios.create({
  baseURL: `http://localhost:8090/`,
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Max-Age': 86400,
    'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkeVlqaERPc0RneGRPT1FoRkZXZ1JQWk05NWZXVzFBVGl1NFFrMkRxM2NBIn0.eyJleHAiOjE2MjY4ODE4MTUsImlhdCI6MTYyNjc5NTQxNSwianRpIjoiMDcxM2VlNWEtMGY1OC00NjNmLWE1YjgtNGJlZjJjOTRmNTYwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL1NwcmluZ0Jvb3QiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImJyb2tlciIsImFjY291bnQiXSwic3ViIjoiMGQwYzAxMWItZTE5OS00MmM3LWI2YjUtNTY5OGJiZDllYWI2IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4iLCJzZXNzaW9uX3N0YXRlIjoiZWVlNzk4NjUtMDExMC00MWRmLTk1OWUtOTRhYWY5ODMxNDhmIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYnJva2VyIjp7InJvbGVzIjpbInJlYWQtdG9rZW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LWFwcGxpY2F0aW9ucyIsInZpZXctY29uc2VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwibWFuYWdlLWNvbnNlbnQiLCJkZWxldGUtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSJ9.gFGOEcEF1ycWI3O3K4AkfREfZdfRKkeJqoz8Pk9C3wUjAM0ITb6NakoyqZy4J_T_PpRxSAbu0IF0ST2TYdlqUrLpYIh-kDznfhWngyJebINPwwVJzS3JSP6QQB4XmQos5_oNCSEq1Hnnsi373AMjAHk_wY4mMdtPlumhOe8EH9u5bxkTvTpGkCjHU9NaBjHxO1CybdZ9-EXhvCxPSoe7KxRoch9JgqbkDiyjlM25Gor8GrsDuwr_fn1OYbdxPw0_ujEh6xOL1uFXIqFY8el8qsgsak2ZAcb01arOYZojoyiTn0iDzeOYzIyNpMOT6mUsfDIK_yPedvQ5Bq4jPqZ-lA'
  }
})
